---
- name: Install Docker and Docker Compose
  hosts: docker
  become: yes

  tasks:
  - name: Apt Update
    ansible.builtin.apt:
      update_cache: yes
  
  - name: Install Dependencies
    ansible.builtin.apt:
      pkg:
        - apt-transport-https
        - curl
        - ca-certificates
        - software-properties-common

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: Add Repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Add remote "nicleary" user to "docker" group
    user:
      name: "nicleary"
      groups: "docker"
      append: yes

  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Make docker-compose file executable
    file:
      path: /usr/local/bin/docker-compose
      mode: '0755'